### ISSUE TITLE
release 0.4

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Pajarito.jl#208]
after current issues are resolved, docs are updated and we have it working with Julia 0.6 and MPB 0.5

**Comment by mlubin** [comment]
There's no release of JuMP that's compatible with Julia 0.6 and MPB 0.6 yet.

**Comment by chriscoey** [comment]
i think the issues will take a while to resolve anyway

any ETA on JuMP?

**Comment by mlubin** [comment]
No, and there's no reason to synchronize Pajarito's releases with JuMP's releases.

**Comment by chriscoey** [comment]
ok then we will release after the current issues are resolved only

**Comment by mlubin** [comment]
Done: https://github.com/JuliaLang/METADATA.jl/pull/8584
