### ISSUE TITLE
Tag JuMP 0.16 Compatible Version

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/Pajarito.jl#246]
Needed for PowerModels reqs, if #208 will come soon-ish, happy to wait.

**Comment by chriscoey** [comment]
Probably not soon-ish, maybe a month or two I'd expect. There won't be
significant changes (possibly a few options though).

**Comment by chriscoey** [comment]
Revise that to a month at most

**Comment by chriscoey** [comment]
@mlubin what else needs to happen before this?

**Comment by mlubin** [comment]
Is the list of options in the readme up to date?

**Comment by chriscoey** [comment]
i mean, other than me finishing up the remaining issues (which could involve changing options and the readme), is there anything else we need to wait for?

**Comment by mlubin** [comment]
No

**Comment by mlubin** [comment]
Tagged in https://github.com/JuliaLang/METADATA.jl/pull/8584
