### ISSUE TITLE
properly attribute any test instances from benchmark libraries

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Pajarito.jl#319]

**Comment by chriscoey** [comment]
https://github.com/JuliaOpt/JuMP.jl/blob/master/examples/data/README.md

**Comment by chriscoey** [comment]
currently it's just tls5.cbf, but will add some rsyn or syn, and some small socrot problems

**Comment by chriscoey** [comment]
@mlubin if it is only tls5 that we use in test, does that require special attribution? and where should that go?

**Comment by mlubin** [comment]
I would put the details in a comment at the top of tls5.cbf. Any lines starting with ``#`` are ignored according to the CBF format.
```
# Converted by Miles Lubin from MINLPLIB2 (http://www.gamsworld.org/minlp/minlplib2/html/).
# Also available in cblib (http://cblib.zib.de/).
