### ISSUE TITLE
add MI-polynomial example problem

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Pajarito.jl#331]
using [PolyJuMP](https://github.com/JuliaOpt/PolyJuMP.jl/blob/master/test/constraint.jl) 

@blegat I am adding some mixed integer conic example problems to the examples folder in this repo. Do you know of any simple applications of MI-SOS? If not I could just cook up an example problem - @joehuchette and I did this for small one last fall and used Pajarito MISDP to solve it. Is PolyJuMP pretty stable? Some integer variables shouldn't cause an issue should they?

**Comment by blegat** [comment]
Integer variables shouldn't cause any problem, PolyJuMP let JuMP handles the manipulation of expressions of decision variables.

**Comment by chriscoey** [comment]
If I wanted a polynomial with integer coefficients, I can't do that currently, right? I am looking at https://github.com/JuliaOpt/SumOfSquares.jl/blob/master/src/variable.jl#L13 and https://github.com/JuliaOpt/SumOfSquares.jl/blob/master/src/variable.jl#L32 where you let all the JuMP variables for the coefficients be `:Cont`

**Comment by blegat** [comment]
Yes, good point, `@polyvariable` does not work yet.
You could build the polynomial as follows:
```
@polyvar x
p = a + b * x # a and b are integer JuMP variables
```
But of course it would be better to add an option to `@polyvariable` to have Integer variables

**Comment by blegat** [comment]
No this feature definitely deserves to be added :-)

**Comment by joehuchette** [comment]
I have an example or two I can put together.

**Comment by blegat** [comment]
@joehuchette You mean you are planning to make a PR for PolyJuMP to implement this ?

**Comment by chriscoey** [comment]
@joehuchette do you have a small self-contained Julia file for MISOS that we could add to the examples folder?

**Comment by ccoffrin** [comment]
If there are not some established standard cases, I can probably come up with some power system example.

**Comment by chriscoey** [comment]
Thanks Carleton, that would be great.

Do you use PolyJuMP etc for that, or the JuMP NLP interface?

**Comment by ccoffrin** [comment]
I have always used JuMP NLP

**Comment by joehuchette** [comment]
I'll open a PR

**Comment by chriscoey** [comment]
closed by @joehuchette's "PR" https://github.com/JuliaOpt/Pajarito.jl/commit/e3462c6a6fbe74b87207329e52c5b9ba405378e5
