### ISSUE TITLE
add more examples 

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Pajarito.jl#337]
a good source of continuous conic problems, some of which may be adaptable to mixed-integer problems, is [CVXPy examples](http://www.cvxpy.org/en/latest/examples/#advanced-examples)

**Comment by chriscoey** [comment]
To users: if you have a self-contained example Julia file of an interesting mixed-integer convex problem that you solve with Pajarito, please comment in this thread so we can discuss adding it to the examples folder. Much appreciated!

**Comment by royakarimi1993** [comment]
I have a MISDP example that I am able to solve it with YALMIP but when I solve it with Pajarito, I get zero for my variables and objective function. I have been struggling for two days to find the reason but I wasn't successful.

**Comment by chriscoey** [comment]
Ok, can you send me the problem? I'll give it a try. My email is coey@mit.edu

**Comment by royakarimi1993** [comment]
Thank you, Chris, for your time. I will double check the revised code that you send me and let you know about the result.

**Comment by chriscoey** [comment]
The new code with `Int` instead of `Bin` variables seems to fix your problem, and I have created an issue to deal with the Pajarito bug. Thanks!

**Comment by chriscoey** [comment]
The tests now contain some very simple examples, and there are more examples (and more new cones) at https://github.com/chriscoey/PajaritoExtras.jl.
