### ISSUE TITLE
getobjbound for conic_to_LPQP

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Pajarito.jl#338]
@mlubin, in new QP tests
```
QP maximize: Error During Test
  Got an exception of type MethodError outside of a @test
  MethodError: no method matching getobjbound(::MathProgBase.SolverInterface.ConicToLPQPBridge)
  Closest candidates are:
    getobjbound(!Matched::GLPKMathProgInterface.GLPKInterfaceMIP.GLPKMathProgModelMIP) at /home/coey/.julia/v0.5/GLPKMathProgInterface/src/GLPKInterfaceMIP.jl:549
    getobjbound(!Matched::Cbc.CbcMathProgSolverInterface.CbcMathProgModel) at /home/coey/.julia/v0.5/Cbc/src/CbcSolverInterface.jl:190
    getobjbound(!Matched::Mosek.MosekMathProgSolverInterface.MosekLinearQuadraticModel) at /home/coey/.julia/v0.5/Mosek/src/MosekLPQCQPInterface.jl:661

```

**Comment by chriscoey** [comment]
also one test isn't passing there because the answer is a factor of 2 off. it could be caused by maybe forgetting the 2 in the RSOC?

```
getobjectivevalue(m) = 8.022765808609499
QP large (cardls): Test Failed
  Expression: isapprox(getobjectivevalue(m),16.045564,atol=TOL)
```

**Comment by mlubin** [comment]
Try out https://github.com/JuliaOpt/MathProgBase.jl/pull/160 for the ``getobjbound`` issue.

With
```julia
@variable(m, w == 2)
@constraint(m, sum(t.^2) <= u*w)
```
You get ``u >= sum(t.^2)/2``. Is that what you want?

**Comment by chriscoey** [comment]
Yes, I wrote that part correctly.

**Comment by mlubin** [comment]
So the objective is to minimize ``sum(t.^2)/2 + rho*sum(x.^2)/2``?

**Comment by chriscoey** [comment]
Yes

**Comment by mlubin** [comment]
The constraints are being enforced as written:
```
julia> sum(getvalue(t).^2)/2 + rho*sum(getvalue(x).^2)/2
8.022766055303913

julia> getobjectivevalue(m)
8.022766159395793
```

**Comment by chriscoey** [comment]
Then that is the correct objective. But the conic tests pass with objective
twice that, suggesting an issue with conic to lpqp

On Mar 29, 2017 11:00, "Miles Lubin" <notifications@github.com> wrote:

The constraints are being enforced as written:

julia> sum(getvalue(t).^2)/2 + rho*sum(getvalue(x).^2)/2
8.022766055303913

julia> getobjectivevalue(m)
8.022766159395793

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JuliaOpt/Pajarito.jl/issues/338#issuecomment-290117798>,
or mute the thread

**Comment by mlubin** [comment]
That suggests an issue with the conic formulation, not conic to lpqp.

**Comment by chriscoey** [comment]
I don't understand. There is only one formulation.

**Comment by mlubin** [comment]
What solver is reporting 16.045564?

**Comment by chriscoey** [comment]
All.

Could be a bug in pajarito too.

**Comment by mlubin** [comment]
I was testing with mosek above through conic_to_lpqp and it was giving the
right answer.

**Comment by chriscoey** [comment]
OK this seems to be fixed.

Tests passing when on MPB master.
