### ISSUE TITLE
describe return statuses - after MPB and JuMP status changes

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Pajarito.jl#353]
table in readme

**Comment by mlubin** [comment]
don't forget about the NLP algorithm, either in a separate table or by making the statuses consistent

**Comment by mlubin** [comment]
Might as well hold off on this until we redo statuses in MPB

**Comment by chriscoey** [comment]
yes. https://github.com/JuliaOpt/MathProgBase.jl/issues/164

**Comment by chriscoey** [comment]
will happen when docs eventually get done (#385) and MOI is out
