### ISSUE TITLE
default output depends on subp vs sep cuts?

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Pajarito.jl#369]
See https://github.com/JuliaOpt/Pajarito.jl/issues/368.
The solver ``PajaritoSolver(mip_solver=CplexSolver(CPX_PARAM_SCRIND=0),cont_solver=ECOSSolver(verbose=0),prim_cuts_assist=false)`` prints the full timing and diagnostic info, while ``PajaritoSolver(mip_solver=CplexSolver(CPX_PARAM_SCRIND=0),prim_cuts_only=true,solve_relax=false,solve_subp=false)`` does not.

**Comment by chriscoey** [comment]
so what's happening here is that, when we do the warning about the gap being negative, we by default switch to printing full diagnostic info. when we don't detect the negative gap and warn, we don't print extra info.

**Comment by mlubin** [comment]
Ok, makes sense.

**Comment by mlubin** [comment]
Actually, what about printing a small message in this case indicating that full diagnostic info will be displayed?

**Comment by chriscoey** [comment]
OK PR will do this
