### ISSUE TITLE
use SCS warm-starts - after MPB warm-starts fix

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Pajarito.jl#372]

**Comment by chriscoey** [comment]
@mlubin let's chat about this, determine what's missing to make this work.

SCS can use warm-starts, and it may be almost as simple as just implementing `setbvec!` for SCS

**Comment by mlubin** [comment]
Implementing ``setbvec!`` and handling the warm starts internally in SCS.jl is a better idea than having Pajarito manage the warm starts

**Comment by chriscoey** [comment]
exactly what I mean, it seems that SCS just keeps the solution around, and all we should need to do is implement `setbvec!`

**Comment by chriscoey** [comment]
https://github.com/JuliaOpt/SCS.jl/pull/75 implements `setbvec!`

warm-starts for SCS in Pajarito work if you only tell SCS to use warm-starts after the first subproblem solve. needs a SCS fix: see https://github.com/JuliaOpt/SCS.jl/issues/77

**Comment by chriscoey** [comment]
wait for https://github.com/JuliaOpt/MathProgBase.jl/issues/64
