### ISSUE TITLE
Support for MathOptInterface

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/Pajarito.jl#411]
No rush, just need an issue to track status.

**Comment by matbesancon** [comment]
one specificity of Pajarito is that it's directly a MPB.AbstractSolver type being used and exposed.
To bring MOI, several options:
1. Create a MOI.AbstractOptimizer type from scratch and implementing the methods on the side
2. Separating the inner working solver and wrapping it in both a MPB and a MOI wrapper separatly
3. Something else?

**Comment by matbesancon** [comment]
I was looking at the ECOS solver for comparison and realized the same approach was not obvious

**Comment by chriscoey** [comment]
an MOI rewrite of Pajarito is under development at https://github.com/chriscoey/MOIPajarito.jl

**Comment by chriscoey** [comment]
I brought that code into this repo on the new main (default) branch. It is a complete rewrite with a simpler design, and easily extensible for new cones (see [PajaritoExtras.jl](https://github.com/chriscoey/PajaritoExtras.jl) for more cones and examples).
