### ISSUE TITLE
Split off the convex MINLP solver into a separate package

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Pajarito.jl#412]
We'd like to split off the convex MINLP solver into a separate package so that if someone says "I used Pajarito to solve X", this means clearly that they used the conic/extended formulation methods proposed in the papers we've written about Pajarito. The convex MINLP solver is useful as a Julia version of some of the methods implemented in Bonmin, but it's quite separate from the academic work we've done on Pajarito.

Opening this to discuss the split and new potential names.

@chriscoey @ccoffrin @juan-pablo-vielma @emreyamangil

**Comment by emreyamangil** [comment]
@mlubin I have 0 spanish as you know but maybe:

pajarito viejo (confusing but would continue the tradition :))

**Comment by juan-pablo-vielma** [comment]
Googled “pajarito viejo” and the first image was a turkey, so how about “Pavito”?

Juan Pablo

On Jun 11, 2018, at 4:08 PM, Emre Yamangil <notifications@github.com<mailto:notifications@github.com>> wrote:


@mlubin<https://github.com/mlubin> I have 0 spanish as you know but maybe:

pajarito viejo (confusing but would continue the tradition :))

**Comment by ccoffrin** [comment]
I think I like the idea of one algorithm per solver; but does it clash with MOI convention of having less repos?  Also, is there sufficient shared code in current Pajarito algorithms that it is easier to put them in one repo, rather than have a third repo for shared functions?

**Comment by emreyamangil** [comment]
@mlubin oh that sounds great too :) My goal was "old bird", sadly my gaps in Spanish prevented me :)

**Comment by mlubin** [comment]
@ccoffrin, I did a quick check and didn't find anything at all that's shared between the two algorithms. `solver.jl` does the work of dispatching between the conic and the nonlinear solver. As far as I can tell, the implementations are otherwise independent. This change does clash with the new preference for having fewer repos, but we're motivated by a specific instance of miscitation of Pajarito and want to prevent future occurrences.

**Comment by chriscoey** [comment]
I think it should not have Pajarito in the name. There should be no (further) confusion. The only similarity between the NLP and conic algorithms is that they are OA.

Juan Pablo suggested "tweety.jl" the other day. My first instinct was "meh.jl" has a nice ring to it. But then I was thinking about birds and thought of "OArly.jl", pronounced "o rly?" like as in the [owl meme](http://knowyourmeme.com/photos/2109-o-rly).

**Comment by ccoffrin** [comment]
My only condition on this change is that the solver name be resonable.  I will need to refrence it all over the place and may ask a student work improve it from time to time...  Hence, not a big fan of any of the names Chris proposed.  Without putting much thought into it, how about MINLPOA or JEMEZ (the mountain range of Pajarito)?

BTW, I totally know the miscitation you are referring to; I had the same thought. :-)

**Comment by juan-pablo-vielma** [comment]
some suggestions
- “pavo” or “pavito”: pavo means turkey in spanish and pavito is its diminutive ( as pajarito for pajaro = bird). also “cerro pavo” is a small mountain in the JEMEZ range https://listsofjohn.com/customlists?lid=252
- “gallina” or “gallinita: gallina means hen in spanish and there is a “gallina peak” in the JEMEZ range
- “caballo” or “caballito”: means horse in spanish and there is a “caballo mountain” in Jemez
- “Pajarito-Azul” : “blue bird” in spanish. also in Jemez (but in english)
- “gorrion” or “gorrioncito (or “gorrión”): gorrión means sparrow in spanish (and gorrioncito is its diminutive). I searched for birds from los alamos and sparrow was the first one whose spanish translation I recognized https://peecnature.org/learn/nature-guides/bird-guide/




On Jun 12, 2018, at 5:33 AM, Carleton Coffrin <notifications@github.com<mailto:notifications@github.com>> wrote:


My only condition on this change is that the solver name be resonable. I will need to refrence it all over the place and may ask a student work improve it from time to time... Hence, not a big fan of any of the names Chris proposed. Without putting much thought into it, how about MINLPOA or JEMEZ (the mountain range of Pajarito)?

BTW, I totally know the miscitation you are referring to; I had the same thought. :-)

**Comment by chriscoey** [comment]
Any of those except pajarito-azul work for me

**Comment by ccoffrin** [comment]
I'm a fan of sticking to the mountain theme, e.g. pavo, gallina, caballo, and ita/ito variants.  I have a slight inclination to Pavito, due to the phonetic similarity to Pajarito.

**Comment by ccoffrin** [comment]
CC @rb004f

**Comment by emreyamangil** [comment]
Pavito +1 !!

Polyhedral Approximation Via Iterative Traditional Optimization :)

**Comment by mlubin** [comment]
Pavito :+1:

**Comment by chriscoey** [comment]
🦃🍗

**Comment by ccoffrin** [comment]
I thInk Turky also matches Chris’s original sentiment, North American
informal “stupid or inept person.” :-)

**Comment by chriscoey** [comment]
Pavito is at https://github.com/chriscoey/Pavito.jl
It is a rewrite of the NLP algorithm in Pajarito. performance (particularly on MIP-solver-driven method) should be better, unless bugs were introduced. the code is cleaner and more maintainable.

next step is to remove the NLP algorithm from Pajarito and tidy up the readme.

**Comment by bernalde** [comment]
Hey guys, just a follow up small detail after this issue. I think you replaced all the "Pajarito" with "Pavito" in the readme.md file. This is a really small thing and I didn't think it was worth of opening an issue for this, but the readme file for Pajarito talks describes Pavito instead.

**Comment by mlubin** [comment]
Blatant errors in the README are definitely worth an opening an issue for. Thanks for pointing it out.

**Comment by chriscoey** [comment]
thanks! fixed
