### ISSUE TITLE
Use FOSS solvers in examples

### ISSUE THREAD

**Issue by matbesancon** [JuliaOpt/Pajarito.jl#417]
It would be nice to make the free solvers the default in the examples for anyone to run

**Comment by chriscoey** [comment]
Good point. PR welcome

**Comment by matbesancon** [comment]
maybe this one after moving to MOI, otherwise this feels like twice the work

**Comment by chriscoey** [comment]
Closing as there is no longer a separate examples folder here (there is in PajaritoExtras, which is an unofficial extension).
