### ISSUE TITLE
Improved Logging

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/Pajarito.jl#420]
I think the solver would be improved by having some more structured logging controlling the terminal output.

Notable challenges for controlling output include the mixture of `warn` and `printf`.

Possibly in Julia 1.0's native loggers could help improve this.

If the logging is updated then the logging redirection feature can be removed from the tests.

**Comment by chriscoey** [comment]
I've rewritten Pajarito on the new main branch. The printing/warning etc and tests are much simpler, so I'll close this issue for now.
