### ISSUE TITLE
Initial OA of SDP unbounded, cannot explain

### ISSUE THREAD

**Issue by bcdandurand** [JuliaOpt/Pajarito.jl#425]
I formulated a MISDP using JuMP, with Mosek as the continuous convex solver and CPLEX as the MIP solver. All decision variables are bounded with absolute value no greater than 1.

How is it that I'm getting this warning?

Warning: Initial conic relaxation status was Unbounded
Warning: MIP solver returned status Unbounded and the conic relaxation solve failed; use a conic solver that succeeds on the relaxation (or submit an issue)
Warning: Not solved to optimality, status: UnboundedOA

To formulate the SDP constraints, I do the following:

@expression(mMP, C[i=1:(2*nbuses),j=1:(2*nbuses)], 0)
...
[augment the entry-wise expressions as linear expressions of the bounded decision variables]
...
@SDconstraint(mMP, C >= 0)

None of the binary variables occur directly in the expressions defining the entries of C, but they occur in other linear constraints of the model mMP that restrict the continuous variables that do occur in the expressions of expression matrix C.

If I code out the constraint @SDconstraint(mMP, C >= 0), the resulting relaxed problem solves normally.

What am I missing? Let me know if more detail on the implementation can help resolve this issue.

**Comment by bcdandurand** [comment]
I also tried implementing the SD constraints as

@variable(mMP, H[i=1:(2*nbuses),j=1:(2*nbuses)], SDP)
@constraint(mMP, SetH[i=1:(2*nbuses),j=i:(2*nbuses)], C[i,j] - H[i,j] == 0)

**Comment by chriscoey** [comment]
Can you share a MWE that I can try running?
Also use backticks around your code in GitHub posts to improve formatting and avoid pinging random users with @

**Comment by bcdandurand** [comment]
As I was creating a minimal example, I found that if I commented out the part of the objective function that had variables that did not appear in the matrix that needs to be PSD, the resulting problem was solved optimally. 

Since these variables (call them zeta) are nonnegative, I created another SD constraint that required a diagonal matrix with these zeta variables on the diagonal entries to be PSD, ie,

'@SDconstraint(mMP, Diag[zeta1,zeta2,...,zetaN] >= 0)

and the problem seems to be resolved.

If possible, in future releases, it might be nice to have this handled automatically, where variables that are not referred to in a matrix expression that needs to be PSD are automatically placed in another diagonal matrix expression that is enforced to be PSD corresponding to, say, nonnegativity constraints.

You may close this issue at your discretion. Thank you.

**Comment by chriscoey** [comment]
It should not be necessary to use a diagonal PSD constraint in that situation. You should be able to just model using nonnegativity (orthant) constraints. I have no idea what caused your issue (it could be a bug in JuMP rather than Pajarito).
