### ISSUE TITLE
MINLP problem

### ISSUE THREAD

**Issue by hect1995** [JuliaOpt/Pajarito.jl#429]
Can a MINLP problem be solved with Pajarito? I have a non-convex cost function, some kinematics of a vehicle that are non linear and the space where the vehicle moves is non-convex and I want to perform collision avoidance in my optimization

**Comment by odow** [comment]
Pajarito is for mixed integer conic programs. 

If you can formulate your problem as a mixed-integer convex NLP, you could use: https://github.com/JuliaOpt/Pavito.jl

If it is really non-convex, you should look at https://github.com/lanl-ansi/Juniper.jl

**Comment by odow** [comment]
Closing as stale and because this isn't a bug in Pajarito.
