### ISSUE TITLE
extremely slow tests since Julia 1.0

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Pajarito.jl#434]
https://travis-ci.org/JuliaOpt/Pajarito.jl/jobs/648157644?utm_medium=notification&utm_source=github_status

Although CI was passing on Julia 1 about 8 months ago (see https://travis-ci.org/JuliaOpt/Pajarito.jl/builds/541010312?utm_medium=notification&utm_source=github_status), now Travis dies on Julia 1.0 - 1.3. It seems to be timing out on a SOC problem with GLPK and SCS - truncated output below:
```
SOC models/solver: Iter, GLPK, SCS
SOC optimal                   ... :Optimal          21.60 s
SOC infeasible                ... :Infeasible        0.01 s
SOCRot optimal                ... :Optimal          31.74 s
SOCRot infeasible             ... :Infeasible        0.00 s
Equality constraint           ... :Optimal           0.00 s
Zero cones                    ... :Optimal           0.00 s
SOC infeasible binary         ... :Infeasible        0.25 s
SOC index bug (#418)          ... 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```

I'm not sure why.

**Comment by ccoffrin** [comment]
Running locally on my computer, `SOC index bug (#418)          ...` does complete but takes about  530 seconds, which is consistent with the termination message.  This only appears to happen in Julia >= 1.0, which is a mystery (possibly newer versions of the solver?  for example SCS has had many changes in Julia v1).

In any case, the tests should be revised so be faster running in Julia v1.0.

**Comment by chriscoey** [comment]
I am reproducing that locally too. I'll look into it more.

**Comment by ccoffrin** [comment]
You might have a look at these solver setting changes I had to make for SCS recently.

https://github.com/lanl-ansi/PowerModels.jl/commit/a0471898bc5f98768c3ffe78fb414293b4a20981#diff-fce720c43af3c52c862fd7451c7374b8
